//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodingChallenge.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormasIdiomas
    {
        public int Id { get; set; }
        public int IdForma { get; set; }
        public int IdIdioma { get; set; }
        public string Singular { get; set; }
        public string Plural { get; set; }
    }
}
