//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodingChallenge.Data.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CodingChallengeEntities : DbContext
    {
        public CodingChallengeEntities()
            : base("name=CodingChallengeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Idiomas> Idiomas { get; set; }
        public virtual DbSet<FormasIdiomas> FormasIdiomas { get; set; }
        public virtual DbSet<Formas> Formas { get; set; }
        public virtual DbSet<Traducciones> Traducciones { get; set; }
    }
}
