//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodingChallenge.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traducciones
    {
        public int Id { get; set; }
        public int IdIdioma { get; set; }
        public string ListaVacia { get; set; }
        public string ReporteDeFormas { get; set; }
        public string Total { get; set; }
        public string Perimetro { get; set; }
        public string Area { get; set; }
        public string Formas { get; set; }
    }
}
